package com.example.trailsnapv2.entities

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Represents a Walk entity stored in the "walks" table of the database.
 * Each walk is associated with a user and contains details about the walk, including distance, start and end times, and an optional photo path.
 *
 * @property walk_id The unique identifier for the walk. This is auto-generated by Room.
 * @property user_id The ID of the user who performed the walk. This is a foreign key reference to the User table.
 * @property walk_name The name or title of the walk.
 * @property distance The distance covered during the walk, in kilometers or miles.
 * @property start_time The start time of the walk, represented as a Unix timestamp (milliseconds).
 * @property end_time The end time of the walk, represented as a Unix timestamp (milliseconds).
 * @property photo_path An optional field storing the path to the photo associated with the walk.
 */
@Entity(
    tableName = "walks",
    foreignKeys = [
        ForeignKey(
            entity = User::class,
            parentColumns = ["user_id"],
            childColumns = ["user_id"],
            onDelete = ForeignKey.CASCADE
        )
    ],
    indices = [Index(value = ["user_id"])]
)
data class Walk(
    @PrimaryKey(autoGenerate = true) val walk_id: Long = 0,
    val user_id: Long,
    val walk_name: String,
    val distance: Double,
    val start_time: Long,
    val end_time: Long,
    val photo_path: String? = null // Novo campo para o caminho da foto
)
